# Generated by Django 4.0 on 2023-02-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='problemData',
            fields=[
                ('problem_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('salary', models.CharField(blank=True, max_length=255, null=True)),
                ('place', models.CharField(blank=True, max_length=255, null=True)),
                ('education', models.CharField(blank=True, max_length=255, null=True)),
                ('experience', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('scale', models.CharField(blank=True, max_length=255, null=True)),
                ('href', models.CharField(blank=True, max_length=255, null=True)),
                ('key_word', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'problem_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpiderInfo',
            fields=[
                ('spider_id', models.AutoField(primary_key=True, serialize=False)),
                ('spider_name', models.CharField(blank=True, max_length=255, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('page', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'spider_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('user_id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pass_word', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'user_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SendList',
            fields=[
                ('send_id', models.AutoField(primary_key=True, serialize=False)),
                ('problem_id', models.IntegerField(blank=True, null=True)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
