# Generated by Django 3.2.23 on 2025-01-03 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_auto_20230409_1134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problemdata',
            options={'managed': False, 'verbose_name': '题目表', 'verbose_name_plural': '题目表'},
        ),
        migrations.AlterModelOptions(
            name='sendlist',
            options={'managed': False, 'verbose_name': '投递信息表', 'verbose_name_plural': '投递信息表'},
        ),
        migrations.AlterModelOptions(
            name='userexpect',
            options={'managed': False, 'verbose_name': '用户期望表', 'verbose_name_plural': '用户期望表'},
        ),
        migrations.AlterModelOptions(
            name='userlist',
            options={'managed': False, 'verbose_name': '用户信息表', 'verbose_name_plural': '用户信息表'},
        ),
        migrations.AlterModelTable(
            name='problemdata',
            table='problem_set',
        ),
        migrations.AlterModelTable(
            name='sendlist',
            table='accept_list',
        ),
    ]
