# Generated by Django 4.2.20 on 2025-04-29 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_auto_20250103_1208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sendlist',
            options={'managed': False, 'verbose_name': '提交信息表', 'verbose_name_plural': '提交信息表'},
        ),
        migrations.AlterModelOptions(
            name='userexpect',
            options={'managed': False, 'verbose_name': '用户期望表', 'verbose_name_plural': '用户期望表'},
        ),
    ]
